
name: shell.yml

on:
  workflow_dispatch:
    inputs:
      release:
        description: 'FreeBSD release'
        required: true
        type: choice
        options:
        - '15.0'
        - '14.2'
        - '14.1'
        - '14.0'
        - '13.5'
        - '13.4'
        - '13.3'
        - '13.2'
        - '12.4'
        default: '15.0'

jobs:
  runshell:
    runs-on: ubuntu-22.04
    name: Start a freebsd shell
    steps:
    - name: Starting a freebsd VM, please wait. It may take 2-3 minutes
      uses: vmactions/freebsd-vm@main
      with:
        release: ${{ github.event.inputs.release || '14.1' }}
        sync: sshfs
        run: |
          freebsd-version
          (ls -lah)
    - uses: mxschmitt/action-tmate@v3
      with:
        limit-access-to-actor: true
