
name: shell.yml

on: workflow_dispatch

jobs:
  runshell:
    runs-on: ubuntu-latest
    name: Start a freebsd shell
    steps:
    - name: Starting a freebsd VM, please wait. It may take 5 minutes
      uses: vmactions/freebsd-vm@main
      with:
        sync: sshfs
        prepare: pkg install -y socat curl
        run: |
          freebsd-version
          (ls -lah)
    - uses: neilpang/debugger-action@master
